import { z } from "zod";

export const validationSchemas = {
  step1: z.object({
    year: z.string().nonempty("Year is required"),
    a1: z.string(),

    a2_1: z.coerce.boolean({ strict: true }),
    a2_2: z.coerce.boolean({ strict: true }),
    a2_3: z.coerce.boolean({ strict: true }),
    a2_4: z.coerce.boolean({ strict: true }),
    a2_5: z.coerce.boolean({ strict: true }),
    a2_6: z.coerce.boolean({ strict: true }),
    a2_7: z.coerce.boolean({ strict: true }),
    a2_8: z.coerce.boolean({ strict: true }),
    a2_9: z.coerce.boolean({ strict: true }),
    a2_10: z.coerce.boolean({ strict: true }),
    a2_11: z.coerce.boolean({ strict: true }),
    a2_12: z.coerce.boolean({ strict: true }),
    a2_13: z.coerce.boolean({ strict: true }),

    a3_1: z.coerce.boolean({ strict: true }),
    a3_2: z.coerce.boolean({ strict: true }),
    a3_3: z.coerce.boolean({ strict: true }),
    a3_4: z.coerce.boolean({ strict: true }),
    a3_5: z.coerce.boolean({ strict: true }),
    a3_6: z.coerce.boolean({ strict: true }),
    a3_7: z.coerce.boolean({ strict: true }),
    a3_8: z.coerce.boolean({ strict: true }),
    a3_9: z.coerce.boolean({ strict: true }),
    a3_10: z.coerce.boolean({ strict: true }),
    a3_11: z.coerce.boolean({ strict: true }),
    a3_12: z.coerce.boolean({ strict: true }),

    a3_13: z.coerce.boolean({ strict: true }),
    a4_1: z.coerce.boolean({ strict: true }),
    a4_2: z.coerce.boolean({ strict: true }),
    a4_3: z.coerce.boolean({ strict: true }),
    a4_4: z.coerce.boolean({ strict: true }),
    a4_5: z.coerce.boolean({ strict: true }),
    a4_6: z.coerce.boolean({ strict: true }),
    a4_7: z.coerce.boolean({ strict: true }),
    a4_8: z.coerce.boolean({ strict: true }),
    a4_9: z.coerce.boolean({ strict: true }),
    a4_10: z.coerce.boolean({ strict: true }),
    a4_11: z.coerce.boolean({ strict: true }),
    a4_12: z.coerce.boolean({ strict: true }),
    a4_13: z.coerce.boolean({ strict: true }),

    a5_1_1: z.coerce.boolean({ strict: true }),
    a5_1_2: z.coerce.boolean({ strict: true }),
    a5_1_3: z.coerce.boolean({ strict: true }),
    a5_1_4: z.coerce.boolean({ strict: true }),
    a5_1_5: z.coerce.boolean({ strict: true }),
    a5_2_1: z.coerce.boolean({ strict: true }),
    a5_2_2: z.coerce.boolean({ strict: true }),
    a5_2_3: z.coerce.boolean({ strict: true }),
    a5_2_4: z.coerce.boolean({ strict: true }),
    a5_2_5: z.coerce.boolean({ strict: true }),
    a5_3_1: z.coerce.boolean({ strict: true }),
    a5_3_2: z.coerce.boolean({ strict: true }),
    a5_3_3: z.coerce.boolean({ strict: true }),
    a5_3_4: z.coerce.boolean({ strict: true }),
    a5_3_5: z.coerce.boolean({ strict: true }),
    a5_4_1: z.coerce.boolean({ strict: true }),
    a5_4_2: z.coerce.boolean({ strict: true }),
    a5_4_3: z.coerce.boolean({ strict: true }),
    a5_4_4: z.coerce.boolean({ strict: true }),
    a5_4_5: z.coerce.boolean({ strict: true }),
    a5_5_1: z.coerce.boolean({ strict: true }),
    a5_5_2: z.coerce.boolean({ strict: true }),
    a5_5_3: z.coerce.boolean({ strict: true }),
    a5_5_4: z.coerce.boolean({ strict: true }),
    a5_5_5: z.coerce.boolean({ strict: true }),
    a5_6_1: z.coerce.boolean({ strict: true }),
    a5_6_2: z.coerce.boolean({ strict: true }),
    a5_6_3: z.coerce.boolean({ strict: true }),
    a5_6_4: z.coerce.boolean({ strict: true }),
    a5_6_5: z.coerce.boolean({ strict: true }),
    a5_7_1: z.coerce.boolean({ strict: true }),
    a5_7_2: z.coerce.boolean({ strict: true }),
    a5_7_3: z.coerce.boolean({ strict: true }),
    a5_7_4: z.coerce.boolean({ strict: true }),
    a5_7_5: z.coerce.boolean({ strict: true }),
    a5_8_1: z.coerce.boolean({ strict: true }),
    a5_8_2: z.coerce.boolean({ strict: true }),
    a5_8_3: z.coerce.boolean({ strict: true }),
    a5_8_4: z.coerce.boolean({ strict: true }),
    a5_8_5: z.coerce.boolean({ strict: true }),
    a5_9_1: z.coerce.boolean({ strict: true }),
    a5_9_2: z.coerce.boolean({ strict: true }),
    a5_9_3: z.coerce.boolean({ strict: true }),
    a5_9_4: z.coerce.boolean({ strict: true }),
    a5_9_5: z.coerce.boolean({ strict: true }),
    a5_10_1: z.coerce.boolean({ strict: true }),
    a5_10_2: z.coerce.boolean({ strict: true }),
    a5_10_3: z.coerce.boolean({ strict: true }),
    a5_10_4: z.coerce.boolean({ strict: true }),
    a5_10_5: z.coerce.boolean({ strict: true }),
    a5_11_1: z.coerce.boolean({ strict: true }),
    a5_11_2: z.coerce.boolean({ strict: true }),
    a5_11_3: z.coerce.boolean({ strict: true }),
    a5_11_4: z.coerce.boolean({ strict: true }),
    a5_11_5: z.coerce.boolean({ strict: true }),
    a5_12_1: z.coerce.boolean({ strict: true }),
    a5_12_2: z.coerce.boolean({ strict: true }),
    a5_12_3: z.coerce.boolean({ strict: true }),
    a5_12_4: z.coerce.boolean({ strict: true }),
    a5_12_5: z.coerce.boolean({ strict: true }),
    a5_13_1: z.coerce.boolean({ strict: true }),
    a5_13_2: z.coerce.boolean({ strict: true }),
    a5_13_3: z.coerce.boolean({ strict: true }),
    a5_13_4: z.coerce.boolean({ strict: true }),
    a5_13_5: z.coerce.boolean({ strict: true }),
  }),
  step2: z.object({
    b1: z.string(),

    b2_1: z.coerce.boolean({ strict: true }),
    b2_2: z.coerce.boolean({ strict: true }),
    b2_3: z.coerce.boolean({ strict: true }),
    b2_4: z.coerce.boolean({ strict: true }),
    b2_5: z.coerce.boolean({ strict: true }),
    b2_6: z.coerce.boolean({ strict: true }),
    b2_7: z.coerce.boolean({ strict: true }),
    b2_8: z.coerce.boolean({ strict: true }),
    b2_9: z.coerce.boolean({ strict: true }),
    b2_10: z.coerce.boolean({ strict: true }),
    b2_11: z.coerce.boolean({ strict: true }),
    b2_12: z.coerce.boolean({ strict: true }),
    b2_13: z.coerce.boolean({ strict: true }),
    b2_14: z.coerce.boolean({ strict: true }),

    b3_1: z.coerce.boolean({ strict: true }),
    b3_2: z.coerce.boolean({ strict: true }),
    b3_3: z.coerce.boolean({ strict: true }),
    b3_4: z.coerce.boolean({ strict: true }),
    b3_5: z.coerce.boolean({ strict: true }),
    b3_6: z.coerce.boolean({ strict: true }),
    b3_7: z.coerce.boolean({ strict: true }),
    b3_8: z.coerce.boolean({ strict: true }),
    b3_9: z.coerce.boolean({ strict: true }),
    b3_10: z.coerce.boolean({ strict: true }),
    b3_11: z.coerce.boolean({ strict: true }),
    b3_12: z.coerce.boolean({ strict: true }),
    b3_13: z.coerce.boolean({ strict: true }),
    b3_14: z.coerce.boolean({ strict: true }),
    b3_15: z.coerce.boolean({ strict: true }),

    b4: z.string(),
  }),
  step3: z.object({
    c1: z.string().nonempty("C.1 is required"),
    c2: z.string().optional(),
    c3: z.string().optional(),
    c4_1: z.coerce.boolean({ strict: true }),
    c4_2: z.coerce.boolean({ strict: true }),
    c4_3: z.coerce.boolean({ strict: true }),
    c4_4: z.coerce.boolean({ strict: true }),
    c4_5: z.coerce.boolean({ strict: true }),
    c4_6: z.coerce.boolean({ strict: true }),
    c5: z.string().optional(),
    c6: z.string().optional(),
  }),

  step4: z.object({
    d1: z.string(),
    d2: z.string(),
    d3: z.string(),
    d4: z.string(),
    d5: z.string(),
    d6: z.string(),
    d7: z.string(),
    d8: z.string(),
    d9: z.string(),
    d10_1: z.coerce.boolean({ strict: true }),
    d10_2: z.coerce.boolean({ strict: true }),
    d10_3: z.coerce.boolean({ strict: true }),
    d10_4: z.coerce.boolean({ strict: true }),
    d10_5: z.coerce.boolean({ strict: true }),
    d10_6: z.coerce.boolean({ strict: true }),
    d10_7: z.coerce.boolean({ strict: true }),
    d10_8: z.coerce.boolean({ strict: true }),
    d10_9: z.coerce.boolean({ strict: true }),
    d10_10: z.coerce.boolean({ strict: true }),
    d10_11: z.coerce.boolean({ strict: true }),
    d10_12: z.coerce.boolean({ strict: true }),
    d10_13: z.coerce.boolean({ strict: true }),
    d10_14: z.coerce.boolean({ strict: true }),
  }),
};
